'use client';

import { User } from '@/types';
import { AlignmentType, BorderStyle, Document, HeadingLevel, Packer, Paragraph, TextRun } from 'docx';
import { saveAs } from 'file-saver';

interface WritingTaskData {
  student: User;
  sectionTitle: string;
  task1?: string;
  task2?: string;
  submittedAt: string;
}

/**
 * Generate and download a DOCX file containing student's Writing Task 1 and Task 2 answers
 */
export async function generateWritingDOCX(data: WritingTaskData) {
  const { student, sectionTitle, task1, task2, submittedAt } = data;

  // Calculate word counts
  const task1WordCount = task1 ? task1.trim().split(/\s+/).filter(w => w).length : 0;
  const task2WordCount = task2 ? task2.trim().split(/\s+/).filter(w => w).length : 0;

  const submittedDate = new Date(submittedAt).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
  });

  // Create document sections
  const sections: Paragraph[] = [];

  // Header
  sections.push(
    new Paragraph({
      text: 'IELTS Writing Section - Student Response',
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    })
  );

  // Student Information
  sections.push(
    new Paragraph({
      children: [
        new TextRun({ text: 'Student Name: ', bold: true }),
        new TextRun({ text: `${student.firstName || ''} ${student.lastName || student.username}` }),
      ],
      spacing: { after: 200 },
    })
  );

  sections.push(
    new Paragraph({
      children: [
        new TextRun({ text: 'Username: ', bold: true }),
        new TextRun({ text: student.username }),
      ],
      spacing: { after: 200 },
    })
  );

  sections.push(
    new Paragraph({
      children: [
        new TextRun({ text: 'Exam Section: ', bold: true }),
        new TextRun({ text: sectionTitle }),
      ],
      spacing: { after: 200 },
    })
  );

  sections.push(
    new Paragraph({
      children: [
        new TextRun({ text: 'Submitted: ', bold: true }),
        new TextRun({ text: submittedDate }),
      ],
      spacing: { after: 400 },
    })
  );

  // Divider
  sections.push(
    new Paragraph({
      border: {
        bottom: {
          color: '000000',
          space: 1,
          style: BorderStyle.SINGLE,
          size: 6,
        },
      },
      spacing: { after: 400 },
    })
  );

  // Task 1
  if (task1) {
    sections.push(
      new Paragraph({
        text: 'Task 1',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 400, after: 200 },
      })
    );

    sections.push(
      new Paragraph({
        children: [
          new TextRun({ text: 'Word Count: ', bold: true }),
          new TextRun({ 
            text: `${task1WordCount} words`,
            color: task1WordCount >= 150 ? '008000' : 'FF0000',
          }),
        ],
        spacing: { after: 200 },
      })
    );

    // Split response into paragraphs
    const task1Paragraphs = task1.split('\n').filter(p => p.trim());
    task1Paragraphs.forEach((para, index) => {
      sections.push(
        new Paragraph({
          text: para,
          spacing: { after: index < task1Paragraphs.length - 1 ? 200 : 400 },
        })
      );
    });
  }

  // Task 2
  if (task2) {
    sections.push(
      new Paragraph({
        text: 'Task 2',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 400, after: 200 },
      })
    );

    sections.push(
      new Paragraph({
        children: [
          new TextRun({ text: 'Word Count: ', bold: true }),
          new TextRun({ 
            text: `${task2WordCount} words`,
            color: task2WordCount >= 250 ? '008000' : 'FF0000',
          }),
        ],
        spacing: { after: 200 },
      })
    );

    // Split response into paragraphs
    const task2Paragraphs = task2.split('\n').filter(p => p.trim());
    task2Paragraphs.forEach((para, index) => {
      sections.push(
        new Paragraph({
          text: para,
          spacing: { after: index < task2Paragraphs.length - 1 ? 200 : 400 },
        })
      );
    });
  }

  // Footer note
  sections.push(
    new Paragraph({
      border: {
        top: {
          color: '000000',
          space: 1,
          style: BorderStyle.SINGLE,
          size: 6,
        },
      },
      spacing: { before: 400, after: 200 },
    })
  );

  sections.push(
    new Paragraph({
      children: [
        new TextRun({
          text: 'This document was generated by the IELTS Mock Platform Admin Panel.',
          italics: true,
          size: 18,
        }),
      ],
      alignment: AlignmentType.CENTER,
    })
  );

  // Create the document
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: sections,
      },
    ],
  });

  // Generate filename
  const namePart = `${student.firstName || ''}_${student.lastName || ''}`.trim().replace(/\s+/g, '_') || student.username;
  const datePart = new Date(submittedAt).toLocaleDateString('en-GB').replace(/\//g, '-');
  const fileName = `Writing_${namePart}_${datePart}.docx`;

  // Generate and download the DOCX file
  const blob = await Packer.toBlob(doc);
  saveAs(blob, fileName);
}
